#ifndef QMLENUMDEF_H
#define QMLENUMDEF_H

#include <QObject>
class QmlEnumDef: public QObject{
    Q_OBJECT
    Q_ENUMS(eVavleParamID)
    Q_ENUMS(eSeqItemType)

public:
    enum eVavleParamID{
        VALVEPARAM_VALVE_MODEL      =  0,
        VALVEPARAM_VALVE_TYPE       = VALVEPARAM_VALVE_MODEL      + 1,
        VALVEPARAM_SEALING_TYPE     = VALVEPARAM_VALVE_TYPE       + 1,
        VALVEPARAM_FLANGE_SIZE      = VALVEPARAM_SEALING_TYPE     + 1,
        VALVEPARAM_METHOD_CONTRACT  = VALVEPARAM_FLANGE_SIZE      + 1,
        VALVEPARAM_BODY_MATERIAL    = VALVEPARAM_METHOD_CONTRACT  + 1,
        VALVEPARAM_COMM_INTERFACE   = VALVEPARAM_BODY_MATERIAL    + 1,
        VALVEPARAM_POWER_OPTION     = VALVEPARAM_COMM_INTERFACE   + 1,
        VALVEPARAM_QUANTITY_SENSORS = VALVEPARAM_POWER_OPTION     + 1,
        VALVEPARAM_VERSION_01       = VALVEPARAM_QUANTITY_SENSORS + 1,
        VALVEPARAM_VERSION_02       = VALVEPARAM_VERSION_01       + 1,
        VALVEPARAM_VERSION_03       = VALVEPARAM_VERSION_02       + 1,
        VALVEPARAM_PRODUCTNUM       = VALVEPARAM_VERSION_03       + 1,
    };

    enum eSeqItemType{
        SEQ_TYPE_OPEN     = 0,
        SEQ_TYPE_CLOSE    = 1,
        SEQ_TYPE_POSITION = 2,
        SEQ_TYPE_CUSTOM   = 3,
        SEQ_TYPE_PRESSURE = 4,
    };
};
#endif // QMLENUMDEF_H
